Cards/Models/Set.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Cards.Models
{
    public class Set
    {
        public Set()
        {
            Date = DateTime.Now;           
        }

        [Key]
        public int SetId { get; set; }
        public DateTime Date { get; private set; }
        
        [Required(ErrorMessage = "Set name is required.")]
        [MaxLength(80, ErrorMessage = "Set name must not exceed 80 characters")]
        public string Name { get; set; }

        [MaxLength(250, ErrorMessage = "Description must not exceed 250 characters.")]
        public string Description { get; set; }

        public Subject Subject { get; set; } = new Subject();
        public List<Card> Cards { get; set; } = new List<Card>();
        public int CardCount
        {
            get
            {
                return Cards.Count;
            }
        }

        public User User { get; set; }

        public string UserId { get; set; }
        //UsersFavourite
    }
}

Cards/ViewModels/Set/AddCardViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class AddCardViewModel
    {
        public Card Card { get; set; } = new Card();
    }
}

Cards/ViewModels/Set/AddSetViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class AddSetViewModel
    {
        public Set Set { get; set; } = new Set();
    }
}

Cards/ViewModels/Set/EditCardViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class EditCardViewModel
    {
        public Card Card { get; set; }
    }
}

Cards/ViewModels/Set/EditSetViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class EditSetViewModel
    {
        public Set Set { get; set; } = new Set();

        public int Id
        {
            get { return Set.SetId; }
            set { Set.SetId = value; }
        }
    }
}

Cards/ViewModels/Set/IndexSetViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class IndexSetViewModel
    {
        public IList<Set> Sets;
        public int SetCount { get
            {
                return Sets.Count;
            }
        }

    }
}

Cards/ViewModels/Set/ShowSetViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class ShowSetViewModel
    {
        public Set Set { get; set; }
        //Cards
        //Card Count
        //Date Created
        //Owner
        //Private
    }
}

Cards/ViewModels/Set/TestViewModel.cs
using Cards.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class TestViewModel
    {
        public Set Set { get; set; }
    }
}

Cards/ViewModels/ShowSetViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Cards.ViewModels
{
    public class ShowSetViewModel
    {
        //Cards
        //Card Count
        //Date Created
        //Owner
        //Private
    }
}

Cards/Controllers/SetController.cs
using Cards.Data;
using Cards.Models;
using Cards.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cards.Controllers
{
    public class SetsController : BaseController
    {        
        /// <summary>
        /// Gets list of all sets ~/sets/
        /// </summary>
        public ActionResult Index()
        {
            var viewModel = new IndexSetViewModel();
            viewModel.Sets = Repository.GetAll();
            return View(viewModel);
        }
        

        /// <summary>
        /// Add a set (get) ~/sets/add
        /// </summary> 
        public ActionResult AddSet()
        {
            var viewModel = new AddSetViewModel();
            return View(viewModel);
        }
        

        /// <summary>
        /// Add a set (post)
        /// </summary> //-- 
        [HttpPost]
        public ActionResult AddSet(AddSetViewModel viewModel)
        {
            var set = new Set();
            set = viewModel.Set;

            Repository.Add(set);

            return RedirectToAction("Index");
        }

        /// <summary>
        /// Gets a set ~/sets/showset/1 
        /// </summary>
        public ActionResult ShowSet(int? setId)
        {
            var set = Repository.Get(setId);

            return View();
        }

        /// <summary>
        /// Deletes a set ~/sets/setid/deleteset
        /// </summary> 
        public ActionResult DeleteSet(int? setId)
        {
            var set = Repository.Get(setId);
            return View(set);
        }

        [HttpPost]
        [ActionName("DeleteSet")]
        public ActionResult DeleteSetPost(int setId)
        {
            Repository.Delete(setId);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Edit a set ~/sets/{setid}/edit
        /// </summary>
        public ActionResult EditSet(int? setId)
        {
            var set = Repository.Get(setId);
            var viewModel = new EditSetViewModel();
            viewModel.Set = set;
            return View(viewModel);
        }
        

        /// <summary>
        /// Edit a set (post)
        /// </summary>
        [HttpPost]
        public ActionResult EditSet(EditSetViewModel viewModel, int setId)
        {
            if (ModelState.IsValid)
            {
                var set = viewModel.Set;
                set.SetId = setId;
                Repository.Edit(set);
                return RedirectToAction("Index");
            }
            return View(viewModel);
        }


        /// <summary>
        /// Add card to set (get) ~/sets/{setId}/add
        /// </summary>
        public ActionResult AddCard(int setId)
        {
            var modelView = new Card()
            {

            };

            return View(modelView);
        }


        /// <summary>
        /// Add card to set (post)
        /// </summary>
        [HttpPost]
        public ActionResult AddCard(Card viewModel)
        {
            return View();
        }


        /// <summary>
        /// Edit card in set ~/sets/{setid}/{cardid}/edit
        /// </summary>
        public ActionResult EditCard(int setId, int cardId)
        {
            var viewModel = new Card()
            {

            };
            return View();
        }
       

        /// <summary>
        /// Edit card in set (post)
        /// </summary>
        [HttpPost]
        public ActionResult EditCard() //addcardviewmodel
        {
            return View();
        }

        /// <summary>
        /// Delete card in set ~/sets/{setid}/{cardid}/delete
        /// </summary>
        public ActionResult DeleteCard(int setId, int cardId)
        {
            return View();
        }
        
    }
}

Cards/Controllers/SetsController.cs
using Cards.Data;
using Cards.Models;
using Cards.Security;
using Cards.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Cards.Controllers
{
    public class SetsController : BaseController
    {
        private SetRepository _setRepository;
        private CardRepository _cardRepository;
        private SubjectRepository _subjectRepository;
        private readonly ApplicationUserManager _userManager = null;

        public SetsController(ApplicationUserManager userManager,
                            SetRepository setRepository, 
                            CardRepository cardRepository,
                            SubjectRepository subjectRepository,
                            Context context)
            :base(context)
        {
            _setRepository = setRepository;
            _cardRepository = cardRepository;
            _userManager = userManager;
            _subjectRepository = subjectRepository;
        }

        /// <summary>
        /// Gets list of all sets ~/sets/
        /// </summary>
        public ActionResult Index()
        {
            var viewModel = new IndexSetViewModel
            {
                Sets = _setRepository.GetAll()
            };
            return View(viewModel);
        }
        
        public ActionResult UserSet()
        {
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("SignIn", "User");
            }

            string userId = User.Identity.GetUserId();
            var viewModel = new IndexSetViewModel
            {
                Sets = _setRepository.GetAllUser(userId)
            };

            ViewBag.Title = "Your Sets";
            return View(viewModel);
        }

        /// <summary>
        /// Add a set (get) ~/sets/add
        /// </summary> 
        public ActionResult AddSet()
        {
            //Check to see if user is logged in
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("SignIn", "User");
            }

            var viewModel = new AddSetViewModel();
            return View(viewModel);
        }
              
        /// <summary>
        /// Add a set (post)
        /// </summary> //-- 
        [HttpPost]
        public ActionResult AddSet(AddSetViewModel viewModel)
        {
            //Double check to see if a user is logged in
            if (!User.Identity.IsAuthenticated)
            {
               return RedirectToAction("SignIn", "User");
            }
            
            //Form validation
            if (!ModelState.IsValid)
            {
                return View(viewModel);
            }

            //Create set to upload to db
            var set = new Set();
            set = viewModel.Set;

            //Check to see if subject already exists
            var subject = (_subjectRepository.DoesSubjectExist(set.Subject.Name)) ? _subjectRepository.GetByName(set.Subject.Name) : set.Subject;
            set.Subject = subject;

            //Attach user to set
            var userId = User.Identity.GetUserId();
            set.UserId = userId;
            set.User = _userManager.FindById(userId);

            _setRepository.Add(set);
            return RedirectToAction("Index");
        }

        /// <summary>
        /// Gets a set ~/sets/showset/1 
        /// </summary>
        public ActionResult ShowSet(int? setId)
        {
            if (setId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var set = _setRepository.Get(setId);
            var viewModel = new ShowSetViewModel
            {
                Set = set
            };
            return View(viewModel);
        }


        /// <summary>
        /// Deletes a set ~/sets/setid/deleteset
        /// </summary> 
        public ActionResult DeleteSet(int? setId)
        {
            if (setId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Check to see if user is logged in
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("SignIn", "User");               
            }

            //Check to see if user is the owner
            var set = _setRepository.Get(setId);
            var userId = User.Identity.GetUserId();
            if (set.UserId != userId)
            {
                return HttpNotFound();
            }

            ViewBag.Set = set;

            return View();
        }

        [HttpPost]
        [ActionName("DeleteSet")]
        public ActionResult DeleteSetPost(int setId)
        {
            //Double check to see if user is logged in
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("SignIn", "User");
            }

            //Double check to see if user is the owner
            var userId = User.Identity.GetUserId();
            if (!_setRepository.EntryOwnedByUser(setId, userId))
            {
                return HttpNotFound();
            }

            if (!ModelState.IsValid)
            {
                return View("Error");
            }
            
            _setRepository.Delete(setId);
            return RedirectToAction("Index");
            
        }
        //To do: Only owner can delete set

        /// <summary>
        /// Edit a set ~/sets/{setid}/edit
        /// </summary>
        public ActionResult EditSet(int? setId)
        {
            if (setId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            //Check if user is signed in before editing
            if (!User.Identity.IsAuthenticated) 
            {
                return RedirectToAction("SignIn", "User");
            }

            //Check if user is the owner before editing
            var userId = User.Identity.GetUserId();           
            var set = _setRepository.Get(setId);
            if(!_setRepository.EntryOwnedByUser(set.SetId, set.UserId)) 
            {
                return HttpNotFound();
            }

            var viewModel = new EditSetViewModel
            {
                Set = set
            };
            return View(viewModel);
        }

        /// <summary>
        /// Edit a set (post)
        /// </summary>
        [HttpPost]                          
        public ActionResult EditSet(EditSetViewModel viewModel)
        {
            //Double check to see if user is authenticated
            if (!User.Identity.IsAuthenticated) 
            {
                return RedirectToAction("SignIn", "User");
            }

            //Create set to upload to db            
            var set = viewModel.Set;
            viewModel.Set.User = _userManager.FindById(set.UserId); 

            var userId = User.Identity.GetUserId();

            //Double check to see user is the owner before posting
            if (!_setRepository.EntryOwnedByUser(set.SetId, userId)) 
            {
                return HttpNotFound();
            }

            //Validate set
            if (!ModelState.IsValid)
            {             
                 return View(viewModel);
            }

            //Check to see if subject already exists
            var subject = (_subjectRepository.DoesSubjectExist(set.Subject.Name)) ? _subjectRepository.GetByName(set.Subject.Name) : set.Subject;
            set.Subject = subject;

            _setRepository.Edit(set);
            return RedirectToAction("Index");
        } 

        //Test mode
        public ActionResult Test(int? setId)
        {
            if (setId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var set = _setRepository.Get(setId);
            var viewModel = new TestViewModel
            {
                Set = set
            };
            return View(viewModel);
        }

        /// <summary>
        /// Add card to set (get) ~/sets/addcard/{setId}
        /// </summary>
        public ActionResult AddCard(int setId)
        {
            //Check to see if user is authenticated
            if (!User.Identity.IsAuthenticated) 
            {
                return RedirectToAction("SignIn", "User");
            }

            //Check to see if user is set owner
            var userId = User.Identity.GetUserId();
            if(!_setRepository.EntryOwnedByUser(setId, userId))
            {
                return HttpNotFound();
            }

            var viewModel = new AddCardViewModel();
            viewModel.Card.SetId = setId;
            return View(viewModel);
        }
        //To do: Only owner can add card to set

        /// <summary>
        /// Add card to set (post)
        /// </summary>
        [HttpPost]
        public ActionResult AddCard(AddCardViewModel viewModel)
        {
            //Double check to see if user is logged in
            if (!User.Identity.IsAuthenticated)
            {
                return RedirectToAction("SignIn", "User");
            }

            //Double check to see if user is set owner
            var userId = User.Identity.GetUserId();
            if (!_setRepository.EntryOwnedByUser(viewModel.Card.SetId, userId))
            {
                return HttpNotFound();
            }

            //Form validation
            if (ModelState.IsValid)
            {
                var card = new Card();
                card = viewModel.Card;
                card.Set = _setRepository.Get(card.SetId);
                _cardRepository.Add(card);
                return RedirectToAction("ShowSet", new { setId = card.SetId });
            }
            return View(viewModel);
        }

        /// <summary>

Cards/Views/Sets/AddCard.cshtml
@model Cards.ViewModels.AddCardViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="card-form-section">
    <h2>Add Card</h2>
    <div id="card-form">
        @using (Html.BeginForm())
        {
        <div class="card-input-cont">
            @Html.LabelFor(m => m.Card.Front)
            @Html.TextBoxFor(m => m.Card.Front)
            @Html.ValidationMessageFor(m => m.Card.Front)
        </div>
        <div class="card-input-cont"> 
            @Html.LabelFor(m => m.Card.Back)
            @Html.TextBoxFor(m => m.Card.Back)
            @Html.ValidationMessageFor(m=>m.Card.Back)
        </div>
        <div class="card-input-cont">
            @Html.LabelFor(m => m.Card.Hint)
            @Html.TextBoxFor(m => m.Card.Hint)
            @Html.ValidationMessageFor(m => m.Card.Hint)
        </div>
            @Html.HiddenFor(m => m.Card.SetId)
            <input type="submit" value="Save Card" class="transition-color" />
        }
    </div>
</div>

Cards/Views/Sets/AddSet.cshtml
@model Cards.ViewModels.AddSetViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="set-form-section">
    <h2>Add Set</h2>
    <div id="set-form">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.Set.UserId)
            <div class="set-input-cont">
                @Html.LabelFor(m => m.Set.Name)<br />
                @Html.TextBoxFor(m => m.Set.Name)
                @Html.ValidationMessageFor(m => m.Set.Name)
            </div>
            <div class="set-input-cont">
                @Html.LabelFor(m => m.Set.Subject.Name)<br />
                @Html.TextBoxFor(m => m.Set.Subject.Name)
                @Html.ValidationMessageFor(m => m.Set.Subject.Name)
            </div>
            <div class="set-input-cont">
                @Html.LabelFor(m => m.Set.Description)<br />
                @Html.TextAreaFor(m => m.Set.Description)
                @Html.ValidationMessageFor(m => m.Set.Description)
            </div>          
            <input type="submit" value="Save Set" class="transition-color" />
        }
    </div>
</div>

Cards/Views/Sets/DeleteCard.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="delete-card-form-section">
    <h2>Delete Card</h2>
    <div id="delete-card-form">
        @using (Html.BeginForm())
        {
            
          <p>Are you sure you want to delete this card?</p>
          <input type="submit" value="Confirm" class="transition-color"/>
            
        }
    </div>
</div>

Cards/Views/Sets/DeleteSet.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="delete-set-form-section">
    <h2>Delete Set</h2>
    <div id="delete-set-form">
        @using (Html.BeginForm())
         {
             <p>
              Are you sure you want to delete "@ViewBag.Set.Name"?
             </p>
             <input type="submit" value="Confirm" class="transition-color"/>
         }
    </div>
</div>

Cards/Views/Sets/EditCard.cshtml
@model Cards.ViewModels.EditCardViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="card-form-section">
    <h2>Edit Card</h2>
    <div id="card-form">
        @using (Html.BeginForm())
        {
            <div class="card-input-cont">
                @Html.LabelFor(m => m.Card.Front)
                @Html.TextBoxFor(m => m.Card.Front)
                @Html.ValidationMessageFor(m => m.Card.Front)
            </div>
            <div class="card-input-cont">
                @Html.LabelFor(m => m.Card.Back)
                @Html.TextBoxFor(m => m.Card.Back)
                @Html.ValidationMessageFor(m => m.Card.Back)
            </div>
            <div class="card-input-cont">
                @Html.LabelFor(m => m.Card.Hint)
                @Html.TextBoxFor(m => m.Card.Hint)
                @Html.ValidationMessageFor(m => m.Card.Hint)
            </div>
            @Html.HiddenFor(m => m.Card.SetId)
            <input type="submit" value="Save Card" class="transition-color" />
        }
    </div>
</div>

Cards/Views/Sets/EditSet.cshtml
@model Cards.ViewModels.EditSetViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="set-form-section">
    <h2>Edit Set</h2>
    <div id="set-form">
        @using (Html.BeginForm())
        {
            @Html.HiddenFor(m => m.Set.UserId)
            <div class="set-input-cont">
                @Html.LabelFor(m => m.Set.Name)<br />
                @Html.TextBoxFor(m => m.Set.Name)
                @Html.ValidationMessageFor(m => m.Set.Name)
            </div>
            <div class="set-input-cont">
                @Html.LabelFor(m => m.Set.Description)<br />
                @Html.TextAreaFor(m => m.Set.Description)
                @Html.ValidationMessageFor(m => m.Set.Description)
            </div>
            <input type="submit" value="Save Set" class="transition-color" />
        }
    </div>
</div>

Cards/Views/Sets/Index.cshtml
@model Cards.ViewModels.IndexSetViewModel
@using Microsoft.AspNet.Identity
@using Cards.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.Title = "All Sets";
}

@{
    string GetTitle()
    {
        var action = ViewContext.RouteData.Values["action"].ToString();
        return (action == "Index") ? "All Sets" : "Your Sets";
    }

    string Visibility()
    {
        var action = ViewContext.RouteData.Values["action"].ToString();
        return (action == "Index") ? "Visible" : "Hidden";
    }
}

<div>
    <div id="set-list-header">
        <h2>@GetTitle()</h2>
        <a href="@Url.Action("AddSet", "Sets")"><img src="~/img/plus.svg" id="add-set-icon" class="transition-everything"/></a>
    </div>

    <ul id="set-list">
        @foreach (var set in Model.Sets)
        {
            <li class="set transition-color">
                <a href="@Url.Action("ShowSet", "Sets", new {SetId = set.SetId})">
                    <div class="set-main">
                        <span class="set-name">@set.Name</span> <span class="set-card-count">@set.CardCount Cards</span>
                    </div>
                    <div class="set-secondary">
                        <span class="set-username"
                              style="visibility:@Visibility()">
                            @set.User.UserName
                        </span>
                    </div>
                </a>
            </li>
        }
    </ul>
</div>

Cards/Views/Sets/ShowSet.cshtml
@model Cards.ViewModels.ShowSetViewModel
@using Microsoft.AspNet.Identity
@using Cards.Models

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    string UserVisibility(Set set)
    {
        var userId = User.Identity.GetUserId();
        return (userId == set.UserId) ? "flex" : "none";
    }

    string DescriptionHelper()
    {
        return (Model.Set.Description == null) ? "No description available" : Model.Set.Description;
    }

    string ExtraMarginIfAuth()
    {
        return (User.Identity.GetUserId() == Model.Set.UserId) ? "owner-card" : "non-owner-card";
    }
}




<div id="showset-container">
    <h2 id="showset-title">@Model.Set.Name</h2>
    <div style="display: @UserVisibility(Model.Set)" id="set-operations">
        
        <a href="@Url.Action("EditSet", "Sets", new {SetId = Model.Set.SetId})"
            id="edit-set-button"
            class="showset-button transition-color">
            Edit Set
        </a>
        <a href="@Url.Action("DeleteSet", "Sets", new {SetId = Model.Set.SetId})"
            id="delete-set-button"
            class="showset-button transition-color">
            Delete Set
        </a>
        
        <a href="@Url.Action("AddCard", "Sets", new {SetId = Model.Set.SetId})"
           id="add-card-button"
           class="showset-button transition-color">
            Add Card
        </a>
    </div>
    <div id="desktop-flex">
        <a href="@Url.Action("Test", "Sets", new { SetId = Model.Set.SetId })"
           id="test-button"
           class="transition-color">
            Test me!
        </a>
        <div>
            <div id="showset-description-show" class="transition-color">Details</div>
            <div id="showset-description">
                <span id="close-description-button" class="transition-color">x</span>
                <h4>Details</h4>
                Description: @DescriptionHelper() <br />
                Owner: @Model.Set.User.UserName <br />
                Subject: @Model.Set.Subject.Name <br />
                Time Created: @Model.Set.Date <br />
                Card Count: @Model.Set.CardCount
            </div>
        </div>
    </div>

    <ul id="card-container">
        @foreach (var card in Model.Set.Cards)
        {
            <li class="card-unit @ExtraMarginIfAuth()">
                <div class="card">
                    <div class="card-front">@card.Front</div>
                    <div class="card-back">@card.Back</div>
                </div>
                <div class="card-operations" style="display: @UserVisibility(Model.Set)">
                    <a href="@Url.Action("EditCard", "Sets", new {SetId = Model.Set.SetId, CardId = card.CardId})"
                       style="display: @UserVisibility(Model.Set)"
                       class="edit-card-button card transition-color">Edit</a>
                    <a href="@Url.Action("DeleteCard", "Sets", new {SetId = Model.Set.SetId, CardId = card.CardId})"
                       style="display: @UserVisibility(Model.Set)"
                       class="delete-card-button transition-color">Delete</a>
                </div>
            </li>

        }
    </ul>
</div>

Cards/Views/Sets/Test.cshtml
@model Cards.ViewModels.TestViewModel

@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";

    string ShowFirstCard(int id)
    {
        return (id != 0) ? "inactive" : null;
    }
}
<div id="cards-container">
    @for(int index = 0; index < Model.Set.Cards.Count; index++)
    { 
        <div id="card-@index" class=@ShowFirstCard(index)>
            <div class="test-card">
                <div class="test-card-inner">
                    <div class="test-card-front unflip-front">
                        @Model.Set.Cards[index].Front
                    </div>
                    <div class="test-card-back unflip-back">
                        @Model.Set.Cards[index].Back
                    </div>
                </div>
            </div>
            <div class="test-btn-container">
                <div class="back-btn transition-color">←</div>
                <div class="fwd-btn transition-color">→</div>
            </div>    
        </div>
    }
</div>

Cards/Views/Sets/UserSet.cshtml
@{
    ViewBag.Title = "Your Sets"; 
}

@Html.Partial("Index");